name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with caliban
      run: sbt test
    - name: Run tests without caliban
      run: sbt ';set g8Properties in g8 in Test ~= { _ ++ Map("add_caliban_endpoint" -> "no") }; test'
    - name: Run tests without sse
      run: sbt ';set g8Properties in g8 in Test ~= { _ ++ Map("add_server_sent_events_endpoint" -> "no") }; test'
    - name: Run tests without optional addons
      run: sbt ';set g8Properties in g8 in Test ~= { _ ++ Map("add_caliban_endpoint" -> "no", "add_server_sent_events_endpoint" -> "no") }; test'
